name: Keep Bot Alive

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Bot
        run: curl -s https://xhost-bot.onrender.com/ > /dev/null
